### PR TITLE
platform: add npth

### PR DESCRIPTION
**Pull request by igor-raits**
If we support pth in Platform, it doesn't make sense to not support
its successor, nPth.

Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>

### CODE REVIEW

**Comment by igor-raits** [comment]
Moreover, I would even argue to **exclude** `pth` from Platform ;)

**Comment by contyk** [comment]
I believe `pth` was necessary to support development against one package or another. We might revisit that. I have nothing against `npth` and would include it.

However, I won't merge this PR. The proper way to update this repo is to

1. update README.md -- add the component to the proper section and add a note about what this component is and why it should be included (keep the syntax & style, it's important)
2. run `make -B` or `make clean && make`; this will regenreate the package litss and data files

Before you can use the package lists in `baseruntime-package-lists`, you also need to run `make hack`, but such lists shouldn't be included in this repo.

I will be adding a `CONTRIBUTING` file that explains the workflow, both here to the other repo.

**Comment by igor-raits** [comment]
@contyk I'm pretty sure you are looking into some wrong commit because this PR does what you are describing.

**Comment by contyk** [comment]
Ok, so we're essentially swapping `pth` for `npth`. I'm okay with that.

**Pull request merged**
